services:
  - docker

script:
  - docker-compose -f docker-compose.common.yml -f docker-compose.test.yml build --no-cache
  - travis_wait docker-compose -f docker-compose.common.yml -f docker-compose.test.yml up